#!/usr/bin/php
<?php

echo "Content-Type: text/plain\r\n";
echo "\r\n";

$t = '';
$t .=  "-- \$_SERVER:\n";
$t .= print_r($_SERVER, true);
$t .= "-- \ENV:\n";
$t .= print_r($_ENV, true);

file_put_contents('git-http-backend.log', $t, FILE_APPEND);
